### ISSUE TITLE
SIGABRT at Interrogator_die

### ISSUE THREAD

**Issue by Civil** [Civil/OpenJK#3]
```
(gdb) bt
#0  0x00007ffff6abe528 in raise () from /lib64/libc.so.6
#1  0x00007ffff6abf97a in abort () from /lib64/libc.so.6
#2  0x00007ffff6ab7417 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007ffff6ab74c2 in __assert_fail () from /lib64/libc.so.6
#4  0x00007fffd75b2357 in Q_irand (min=-10, max=-20) at /home/civil/src/OpenJK/codeJK2/game/../game/../../code/ui/../qcommon/q_shared.h:802
#5  0x00007fffd75bddf0 in Interrogator_die (self=0x7fffd7cf93a0 <g_entities+379456>, inflictor=0x7fffd7c9c960 <g_entities>, attacker=0x7fffd7c9c960 <g_entities>, damage=100, mod=1, dFlags=1048, hitLoc=0)
    at /home/civil/src/OpenJK/codeJK2/game/AI_Interrogator.cpp:72
#6  0x00007fffd76613a1 in player_die (self=0x7fffd7cf93a0 <g_entities+379456>, inflictor=0x7fffd7c9c960 <g_entities>, attacker=0x7fffd7c9c960 <g_entities>, damage=100, meansOfDeath=1, dflags=1048, hitLoc=0)
    at /home/civil/src/OpenJK/codeJK2/game/g_combat.cpp:3762
#7  0x00007fffd766764b in GEntity_DieFunc (self=0x7fffd7cf93a0 <g_entities+379456>, inflictor=0x7fffd7c9c960 <g_entities>, attacker=0x7fffd7c9c960 <g_entities>, damage=100, mod=1, dFlags=1048, hitLoc=0)
    at /home/civil/src/OpenJK/codeJK2/game/g_functions.cpp:383
#8  0x00007fffd76652af in G_Damage (targ=0x7fffd7cf93a0 <g_entities+379456>, inflictor=0x7fffd7c9c960 <g_entities>, attacker=0x7fffd7c9c960 <g_entities>, dir=0x7fffd7e35520 <dmgDir>, point=0x7fffd7e355e0 <dmgSpot>, damage=100, 
    dflags=1048, mod=1, hitLoc=0) at /home/civil/src/OpenJK/codeJK2/game/g_combat.cpp:5424
#9  0x00007fffd76c8ef7 in WP_SaberApplyDamage (ent=0x7fffd7c9c960 <g_entities>, baseDamage=10, baseDFlags=0, brokenParry=0) at /home/civil/src/OpenJK/codeJK2/game/wp_saber.cpp:924
#10 0x00007fffd76d0a1c in WP_SaberDamageTrace (ent=0x7fffd7c9c960 <g_entities>) at /home/civil/src/OpenJK/codeJK2/game/wp_saber.cpp:3468
#11 0x00007fffd764695c in ClientEvents (ent=0x7fffd7c9c960 <g_entities>, oldEventSequence=1053) at /home/civil/src/OpenJK/codeJK2/game/g_active.cpp:1313
#12 0x00007fffd764b32b in ClientThink_real (ent=0x7fffd7c9c960 <g_entities>, ucmd=0x7fffffff797c) at /home/civil/src/OpenJK/codeJK2/game/g_active.cpp:2835
#13 0x00007fffd764bb36 in ClientThink (clientNum=0, ucmd=0x7fffffff797c) at /home/civil/src/OpenJK/codeJK2/game/g_active.cpp:3030
#14 0x0000000000471682 in SV_ClientThink (cl=0x229d4a0, cmd=0x7fffffff797c) at /home/civil/src/OpenJK/code/server/sv_client.cpp:399
#15 0x0000000000471b4b in SV_UserMove (cl=0x229d4a0, msg=0x7fffffff7e20) at /home/civil/src/OpenJK/code/server/sv_client.cpp:520
#16 0x0000000000471c02 in SV_ExecuteClientMessage (cl=0x229d4a0, msg=0x7fffffff7e20) at /home/civil/src/OpenJK/code/server/sv_client.cpp:565
#17 0x000000000047545e in SV_PacketEvent (from=..., msg=0x7fffffff7e20) at /home/civil/src/OpenJK/code/server/sv_main.cpp:348
#18 0x000000000044a6a1 in Com_RunAndTimeServerPacket (evFrom=0x7fffffff7e40, buf=0x7fffffff7e20) at /home/civil/src/OpenJK/code/qcommon/common.cpp:815
#19 0x000000000044a816 in Com_EventLoop () at /home/civil/src/OpenJK/code/qcommon/common.cpp:854
#20 0x000000000044b3af in Com_Frame () at /home/civil/src/OpenJK/code/qcommon/common.cpp:1369
#21 0x00000000004c0a34 in main (argc=1, argv=0x7fffffffd828) at /home/civil/src/OpenJK/shared/sys/sys_main.cpp:789
(gdb) info locals
No locals.
(gdb) frame 5
#5  0x00007fffd75bddf0 in Interrogator_die (self=0x7fffd7cf93a0 <g_entities+379456>, inflictor=0x7fffd7c9c960 <g_entities>, attacker=0x7fffd7c9c960 <g_entities>, damage=100, mod=1, dFlags=1048, hitLoc=0)
    at /home/civil/src/OpenJK/codeJK2/game/AI_Interrogator.cpp:72
72                      self->client->ps.velocity[0] = Q_irand( -10, -20 );
(gdb) info local
No locals.
(gdb) info locals
No locals.
(gdb) frame 6
#6  0x00007fffd76613a1 in player_die (self=0x7fffd7cf93a0 <g_entities+379456>, inflictor=0x7fffd7c9c960 <g_entities>, attacker=0x7fffd7c9c960 <g_entities>, damage=100, meansOfDeath=1, dflags=1048, hitLoc=0)
    at /home/civil/src/OpenJK/codeJK2/game/g_combat.cpp:3762
3762                    Interrogator_die( self, inflictor, attacker, damage, meansOfDeath, dflags, hitLoc );
(gdb) info locals
anim = 0
contents = 0
deathScript = 0
lastInGroup = 0
specialAnim = 0
holdingSaber = 0
cliff_fall = 0
(gdb) frame 7
#7  0x00007fffd766764b in GEntity_DieFunc (self=0x7fffd7cf93a0 <g_entities+379456>, inflictor=0x7fffd7c9c960 <g_entities>, attacker=0x7fffd7c9c960 <g_entities>, damage=100, mod=1, dFlags=1048, hitLoc=0)
    at /home/civil/src/OpenJK/codeJK2/game/g_functions.cpp:383
383             DIECASE( player_die )
(gdb) info locals
No locals.
(gdb) q
```

**Comment by Civil** [comment]
Q_irand called with constant values, so the bug is in the assert clause.
